### ISSUE TITLE
cglib classloader issue

### ISSUE THREAD

**Issue by ckasek** [jhalterman/modelmapper#136]
I'm currently evaluating different options for doing mapping, and ModelMapper was my first candidate.  The app I'd be using this in is a JavaEE6 webservice that uses JAX-RS, EJB, JPA, etc., all running on glassfish.  I'm trying to map from a JPA entity to a pojo i've created, but things are not going well.  I created my own PropertyMap, but as soon as I try to map the object on my app server, it bombs out with:
```
Failed to generate proxy class for com.mypackage.entities.JobPosition. Ensure that com.mypackage.entities.JobPosition has a non-private constructor.
Caused by: org.modelmapper.internal.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.modelmapper.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
	at org.modelmapper.internal.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at org.modelmapper.internal.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
	at org.modelmapper.internal.ProxyFactory.proxyClassFor(ProxyFactory.java:68)
```

In digging around online, I found one person who suggested this fix in a different library that was seeing an issue in dealing with JPA entities:
```
Enhancer enhancer = new Enhancer();
enhancer.setClassLoader(Thread.currentThread().getContextClassLoader());
```

I made this change in the ProxyFactory.proxyClassFor method, my exception went away, and all is well...but I don't know the ramifications of that change, or if there's a better way to go about it, or really what the cause is.  I can try to provide any other info that may be useful...below is the basics of my code, I trimmed down the classes and some of the crazier looking mappings in my PropertyMap.

The offending code:
```
JobPosition jobPosition = jobPositionFacade.find(id);
if (jobPosition != null) {
    ModelMapper modelMapper = new ModelMapper();
    modelMapper.addMappings(new JobPositionDTOMapping());
    JobPositionDTO appDTO = modelMapper.map(jobPosition, JobPositionDTO.class);
}
```

The PropertyMap:
```
public class JobPositionDTOMapping extends PropertyMap<JobPosition, JobPositionDTO> {
    @Override
    protected void configure() {
        map().setJobArea(source.getJobArea().getName());
        map().setJobLocation(source.getJobLocation().getName());
    }
}
```

The JPA Entity:
```
@Entity
@Table(name = "job_position")
public class JobPosition {

    @JoinColumn(name = "job_location_key", referencedColumnName = "serial_key")
    @ManyToOne
    private JobLocation jobLocation;
    
    @JoinColumn(name = "job_area_key", referencedColumnName = "serial_key")
    @ManyToOne
    private JobArea jobArea;
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "serial_key")
    protected Integer serialKey;

    public Integer getSerialKey() {
        return serialKey;
    }

    public void setSerialKey(Integer serialKey) {
        this.serialKey = serialKey;
    }

    public JobArea getJobArea() {
        return jobArea;
    }

    public void setJobArea(JobArea jobArea) {
        this.jobArea = jobArea;
    }

    public JobLocation getJobLocation() {
        return jobLocation;
    }

    public void setJobLocation(JobLocation jobLocation) {
        this.jobLocation = jobLocation;
    }

}
```

The DTO:
```
public class JobPositionDTO {
    private int id;
    private String jobArea;
    private String jobLocation;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getJobArea() {
        return jobArea;
    }

    public void setJobArea(String jobArea) {
        this.jobArea = jobArea;
    }

    public String getJobLocation() {
        return jobLocation;
    }

    public void setJobLocation(String jobLocation) {
        this.jobLocation = jobLocation;
    }

}
```

**Comment by jhalterman** [comment]
AFAIK, setting the thread context classloader should be fine. If it resolves your issue, it's good with me. Do you want to send over a pull request for this?
