### ISSUE TITLE
Reusable Generic PropertyMap

### ISSUE THREAD

**Issue by kdeenanauth** [jhalterman/modelmapper#153]
The following functionality used to work in 0.6.5 but currently breaks.

I have the following class that is intended to be reused to skip certain fields during mapping:
```java
public class SkipAuditPersistMapping<S, T extends AuditPersist> extends PropertyMap<S, T>
{
	/**
	 * {@inheritDoc}
	 *
	 * @see org.modelmapper.PropertyMap#configure()
	 */
	@Override
	protected void configure() {
		skip().setCreateDate(null);
		skip().setCreatedBy(null);
		skip().setModifiedDate(null);
		skip().setModifiedBy(null);
	}
}
```
However given the following scenario:
```java
public class SkipAuditPersistMappingTest
{
	/**
	 * A class that does nothing
	 */
	public static class BoringClass {
		
	}
	
	/**
	 * The {@link AuditedClass} which implements {@link AuditPersist}
	 */
	public static class AuditedClass implements AuditPersist {
		private Date createDate;
		private String createdBy;
		private Date modifiedDate;
		private String modifiedBy;
		
		@Override
		public Date getCreateDate() {
			return createDate;
		}

		@Override
		public void setCreateDate(Date createDate) {
			this.createDate = createDate;
		}

		@Override
		public String getCreatedBy() {
			return this.createdBy;
		}

		@Override
		public void setCreatedBy(String createdBy) {
			this.createdBy = createdBy;
		}

		@Override
		public Date getModifiedDate() {
			return modifiedDate;
		}

		@Override
		public void setModifiedDate(Date modifiedDate) {
			this.modifiedDate = modifiedDate;
		}

		@Override
		public String getModifiedBy() {
			return modifiedBy;
		}

		@Override
		public void setModifiedBy(String modifiedBy) {
			this.modifiedBy = modifiedBy;
		}
		
	}
	
	@Test
	public void testMappingClassWithoutDi() {
		ModelMapper modelMapper = new ModelMapper();
		modelMapper.createTypeMap(BoringClass.class, AuditedClass.class).addMappings(new SkipAuditPersistMapping<BoringClass, AuditedClass>());
		modelMapper.map(new BoringClass(), AuditedClass.class);
	}
}
```

Fails with:
```
org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) A mapping is missing a required destination member.

2) A mapping is missing a required destination member.

3) A mapping is missing a required destination member.

4) A mapping is missing a required destination member.

4 errors
	at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
	at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:229)
	at org.modelmapper.PropertyMap.configure(PropertyMap.java:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:195)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
	at com.rosetta.samsk.hibernate.util.SkipAuditPersistMappingTest.testMappingClassWithoutDi(SkipAuditPersistMappingTest.java:159)
```

**Comment by ttsanev** [comment]
I'm having the same issue, even if I explicitly pass the types in the PropertyMap constructor.

    new FooMap<Foo, Bar>(Foo.class, Bar.class);

**Comment by dai0304** [comment]
I have this issue also on `Converter`s.

**Comment by jhalterman** [comment]
I'd welcome a pull request for this if anyone is up to it.

**Comment by JensRantil** [comment]
@dai0304 #187 might be of interest.
