### ISSUE TITLE
Incorrect instance returned by MappingContext.getSource() in Converter

### ISSUE THREAD

**Issue by mikaelnousiainen** [jhalterman/modelmapper#169]
I'm having problems using a Converter with a hierarchy of objects. I'm trying to use InfoPropertyMap automatically in all properties that need conversion Info to InfoDTO. However, class Info contains class SubInfo, which is completely different from SubInfoDTO, so more complex mapping is needed there, which is why I'm using a Converter for it.

The following test case fails with a ClassCastException on line:

            dto.setSubInfoDtoData(context.getSource().getSubInfoData());

To me this looks like a bug, but I'm still not sure if I'm doing something wrong here...

The test case:
```java
import org.junit.Test;
import org.modelmapper.Converter;
import org.modelmapper.ModelMapper;
import org.modelmapper.PropertyMap;
import org.modelmapper.config.Configuration;
import org.modelmapper.convention.MatchingStrategies;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class ModelMapperTest {
  @Test
  public void test() throws Exception {
    ModelMapper modelMapper = new ModelMapper();

    modelMapper.getConfiguration().
        setFieldAccessLevel(Configuration.AccessLevel.PUBLIC).
        setFieldMatchingEnabled(false).
        setMatchingStrategy(MatchingStrategies.STRICT);

    modelMapper.addMappings(new InfoPropertyMap());

    Container container = new Container();
    container.setInfo(new Info());
    container.getInfo().setSubInfo(new SubInfo());
    container.getInfo().getSubInfo().setSubInfoData("some data");

    ContainerDTO dto = modelMapper.map(container, ContainerDTO.class);
    assertNotNull(dto.getInfo());
    assertEquals(dto.getInfo().getSubInfo().getSubInfoDtoData(), container.getInfo().getSubInfo().getSubInfoData());
  }

  public class InfoPropertyMap extends PropertyMap<Info, InfoDTO> {
    @Override
    protected void configure() {
      Converter<SubInfo, SubInfoDTO> subInfoConverter =
          context -> {
            // Why is context.getSource() an instance of class Container and not of class SubInfo?
            SubInfoDTO dto = new SubInfoDTO();
            // In reality we would have more complex mappings here!
            dto.setSubInfoDtoData(context.getSource().getSubInfoData());
            return dto;
          };

      using(subInfoConverter).map(source).setSubInfo(null);
    }
  }
}

class Container {
  private Info info;

  public Info getInfo() {
    return info;
  }

  public void setInfo(Info info) {
    this.info = info;
  }
}

class Info {
  private SubInfo subInfo;

  public SubInfo getSubInfo() {
    return subInfo;
  }

  public void setSubInfo(SubInfo subInfo) {
    this.subInfo = subInfo;
  }
}

class SubInfo {
  private String subInfoData;

  public String getSubInfoData() {
    return subInfoData;
  }

  public void setSubInfoData(String subInfoData) {
    this.subInfoData = subInfoData;
  }
}

class ContainerDTO {
  private InfoDTO info;

  public InfoDTO getInfo() {
    return info;
  }

  public void setInfo(InfoDTO info) {
    this.info = info;
  }
}

class InfoDTO {
  private SubInfoDTO subInfo;

  public SubInfoDTO getSubInfo() {
    return subInfo;
  }

  public void setSubInfo(SubInfoDTO subInfo) {
    this.subInfo = subInfo;
  }
}

class SubInfoDTO {
  private String subInfoDtoData;

  public String getSubInfoDtoData() {
    return subInfoDtoData;
  }

  public void setSubInfoDtoData(String subInfoDtoData) {
    this.subInfoDtoData = subInfoDtoData;
  }
}
```

The stack trace:
```
org.modelmapper.MappingException: ModelMapper mapping errors:

1) Converter test.ModelMapperTest$InfoPropertyMap$$Lambda$1/1295083508@32eebfca failed to convert test.Info to test.SubInfoDTO.

1 error

	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:374)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:69)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:497)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:340)
	at test.ModelMapperTest.test(ModelMapperTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassCastException: test.Container cannot be cast to test.SubInfo
	at test.ModelMapperTest$InfoPropertyMap.lambda$configure$0(ModelMapperTest.java:42)
	at org.modelmapper.internal.MappingEngineImpl.convert(MappingEngineImpl.java:336)
	at org.modelmapper.internal.MappingEngineImpl.setDestinationValue(MappingEngineImpl.java:240)
	at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:180)
	at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:131)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:101)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:60)
	... 29 more
```

**Comment by mikaelnousiainen** [comment]
I was using PropertyMap API incorrectly, the mapping with Converter from SubInfo to SubInfoDTO should have been:

```java
using(subInfoConverter).map(source.getSubInfo()).setSubInfo(null);
```

So I was supplying an incorrect source object for the converter.
